ENV = "prod"
MYSQL_PORT_NUMBER     = 3306
MYSQL_STORAGE         = 10
MYSQL_ENGINE_VERSION  = "5.7"
MYSQL_INSTANCE_CLASS  = "db.t3.micro"

DOCDB_PORT = 27017
DOCDB_INSTANCE_CLASS = "db.t3.medium"
DOCDB_INSTANCE_COUNT = 1

ELASTICCACHE_PORT = 6379 
ELASTICCACHE_NODE_COUNT = 1
ELASTICCACHE_NODE_TYPE = "cache.t3.small"
ELASTICCACHE_ENGINE_VERSION = "6.x"