ENV = "dev"

MYSQL_PORT_NUMBER     = 3306
MYSQL_STORAGE         = 10
MYSQL_ENGINE_VERSION  = "5.7"
MYSQL_INSTANCE_CLASS  = "db.t3.micro"

//Docdb variable values

DOCDB_PORT = 27017
DOCDB_INSTANCE_CLASS = "db.t3.medium"
DOCDB_INSTANCE_COUNT = 1




